#!/bin/sh
set -x
set -e

if [ -d .tmp/facts_cache ]; then
   rm -rf .tmp/facts_cache
fi


# this step spawns/prepares the instances and generates the
# openshift-ansible-inventory file
ansible-playbook setup-openshift-hosts.yml

# now we checkout openshift-ansible
if [ ! -d openshift-ansible ]; then
  git clone https://github.com/openshift/openshift-ansible
  cd openshift-ansible
  git checkout release-3.11
  cd ..
fi

cd openshift-ansible

# and we deploy using the inventory generated by the first step
# which points to our shiny new instances.

ansible-playbook -i ../openshift-ansible-inventory  playbooks/prerequisites.yml
ansible-playbook -i ../openshift-ansible-inventory  playbooks/deploy_cluster.yml

