---
- name: setup opestack resources
  hosts: 127.0.0.1
  connection: local
  tasks:
    - include_tasks: create-net.yaml
    - include_tasks: create-os-instances.yaml

- name: setup docker, oc client, and prepare hosts for openshift-ansible
  hosts: openshift
  roles:
    - docker
    - oc_client
    - prepare_host_openshift_ansible

- name: debug
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create dictionary for hosts in master group
      set_fact:
        masters: "{{ masters|default([]) + [ item ] }}"
      with_items: "{{ hosts }}"
      when: item.group == "master"

    - name: Create dictionary for hosts in worker group
      set_fact:
        workers: "{{ workers|default([]) + [ item ] }}"
      with_items: "{{ hosts }}"
      when: item.group == "worker"

    - name: Create openshift-ansible inventory
      template:
        src: openshift-ansible-3.11-inventory.j2
        dest: openshift-ansible-inventory


